### ISSUE TITLE
No container local-evaluator

### ISSUE THREAD

**Issue by bhairavmehta95** [duckietown/duckietown-challenges-runner#2]
Despite having the latest version of `dt-challenges-evaluator:v4`, I always get this issue when evaluating locally:

```
ERROR:runner-local:Traceback (most recent call last):
  File "/project/src/duckietown_challenges_runner/runner_local.py", line 34, in runner_local_main
    runner_local_main_()
  File "/project/src/duckietown_challenges_runner/runner_local.py", line 163, in runner_local_main_
    debug_volumes=parsed.debug_volumes)
  File "/project/src/duckietown_challenges_runner/runner.py", line 487, in run_single
    debug_volumes=debug_volumes)
  File "/project/src/duckietown_challenges_runner/runner.py", line 740, in get_config
    br = parse_complete_tag(image)
  File "/project/src/duckietown-challenges/src/duckietown_challenges/cmd_submit_build.py", line 55, in parse_complete_tag
    if '@' in tag:
TypeError: argument of type 'NoneType' is not iterable

**** MAIN ISSUE HERE ****

INFO:dts:Cannot get container local-evaluator: 404 Client Error: Not Found ("No such container: local-evaluator")
```

**Comment by AndreaCensi** [comment]
I fixed this this afternoon; it's a caching problem somewhere.
Is it working now?

**Comment by AndreaCensi** [comment]
what version of duckietown-challenges you have? (should be displayed at the beginning of the output)

**Comment by AndreaCensi** [comment]
@bhairavmehta95 my bad - I had not update the container. pushing now

**Comment by bhairavmehta95** [comment]
Updated, still doesn't work?

**Comment by bhairavmehta95** [comment]
@AndreaCensi still having this issue. I've update shell and duckietown-challenges to the latest versions, but for some reason it gets passed this.

**Comment by bhairavmehta95** [comment]
https://github.com/duckietown/challenge-aido_LF-template-pytorch/blob/aido2-debug/submission.yaml

I'm also seeing this as part of the issue:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/src/duckietown_challenges_runner/runner_local.py", line 34, in runner_local_main
    runner_local_main_()
  File "/project/src/duckietown_challenges_runner/runner_local.py", line 70, in runner_local_main_
    subinfo = read_submission_info(path)
  File "/project/src/duckietown_challenges_runner/submission_build.py", line 57, in read_submission_info
    raise CouldNotReadSubInfo(msg)
duckietown_challenges_runner.submission_build.CouldNotReadSubInfo: Could not read file './submission.yaml': Unused fields ['title', 'tags', 'date-open', 'date-close', 'roles', 'scoring', 'steps', 'transitions'] 
```

but this file was pulled straight from here: https://github.com/duckietown/challenge-aido_LF-baseline-IL-logs-tensorflow

which seems to work okay.
